### ISSUE TITLE
Fomod installer fails quietly

### ISSUE THREAD

**Issue by phen0mX** [limo-app/limo#12] opened 2024-08-25 17:45 UTC
Trying to install [this fomod](https://www.nexusmods.com/newvegas/mods/85957).
"Succeeds" and leaves a clean log:

> 2024-08-25 19:36:55 [Info]: Downloading "Consistent Weapon Mod Descriptions-85957-1-6-1718210638.zip" with size: 30.49KiB...
2024-08-25 19:36:55 [Info]: Download complete
2024-08-25 19:36:55 [Info]: Importing mod '/var/mnt/crucial/Mods/New Vegas/_download/Consistent Weapon Mod Descriptions-85957-1-6-1718210638.zip'
2024-08-25 19:36:55 [Info]: Mod imported

But the mod stays uninstalled and further mod installation is completely blocked.
This includes drag&drop and nxm links.
Only restarting Limo can resolve the blockage.

Also the context menu is completely greyed out, except for "Browse Files":
![Bildschirmfoto vom 2024-08-25 19-57-57](https://github.com/user-attachments/assets/ccf52670-6fdd-45c8-90db-f6b5b4f33950)

**Comment by limo-app** [comment] 2024-08-25 18:15
Can reproduce. This is both a bug with Limo possibly with the mod itself. The FOMOD dialog did not find any files to install, so the installation was aborted. The fact that this is currently silent is a bug, which i have fixed.
However, the underlying issue is that the ModuleConfig.xml file for that mod seems to be malformed. There is a checkbox `Remove Stat Values` in the dialog that sets a flag if checked. If you check that the mod is installed correctly. If not, your issue occurs. This is because the mods fomod file differentiates two cases: If the flag is set to `Active`: Install file A, if the flag is set to an empty string: Install file B. But if you don't check the checkbox, this flag does not exist at all.

The fomod spec isn't does not define default values for flags, so they should not be expected to be an empty string. That being said, i could technically fix this by assuming flags set to empty strings are not set. This depends on how mods mod authors would understand this to work.

**Comment by phen0mX** [comment] 2024-08-25 18:31
Maybe apply the workaround, so users are able to use malformed fomods.
But pop a warning to warn the user and maybe the mod author that this fomod shows potentially undefined/incorrect behaviour?

**Comment by limo-app** [comment] 2024-08-25 18:36
I suppose assuming that an unset tags contains an empty string is reasonable and i will add the warning you mentioned. FOMOD can be a hassle to get correct, since the spec leaves so many things undefined and as a result i have found that a lot of mod authors make small mistakes that have to be accommodated somehow without breaking things for authors that follow the standard.

**Comment by phen0mX** [comment] 2024-08-26 17:11
Exiting out of a fomod installation (the one from my other issue, coincidently) also leads to the blocked UI described in this issue.

**Comment by limo-app** [comment] 2024-08-26 20:06
> Exiting out of a fomod installation (the one from my other issue, coincidently) also leads to the blocked UI described in this issue.

Good catch. These are essentially the same bug and i will push a fix later today.

**Comment by limo-app** [comment] 2024-08-27 21:31
Both of these should be fixed in [1d7129d](https://github.com/limo-app/limo/commit/1d7129de828007ef589de4f3823f510cfd70ef8b).

**Comment by limo-app** [comment] 2024-08-28 23:09
The fixes are now live as part of 1.0.5 on Flathub. Closing

**Closed by limo-app** 2024-08-28 23:09 UTC
Labels: bug
